/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.palscash.wallet.ui.dialog;

/**
 *
 * @author Sergey
 */
public class FreshStart extends javax.swing.JPanel {

    /**
     * Creates new form FreshStart
     */
    public FreshStart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateNewWallet = new javax.swing.JButton();
        btnLoadExistingWallet = new javax.swing.JButton();

        btnCreateNewWallet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus_128.png"))); // NOI18N
        btnCreateNewWallet.setText("Create new wallet");
        btnCreateNewWallet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCreateNewWallet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnLoadExistingWallet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/wallet_128.png"))); // NOI18N
        btnLoadExistingWallet.setText("Open wallet");
        btnLoadExistingWallet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLoadExistingWallet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreateNewWallet, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoadExistingWallet, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoadExistingWallet, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateNewWallet, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCreateNewWallet;
    public javax.swing.JButton btnLoadExistingWallet;
    // End of variables declaration//GEN-END:variables
}
